/*
* generated by Xtext
*/
package ac.soton.awm;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AWMStandaloneSetup extends AWMStandaloneSetupGenerated{

	public static void doSetup() {
		new AWMStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

