/*
* generated by Xtext
*/
package ac.soton.awm.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import ac.soton.awm.services.AWMGrammarAccess;

public class AWMParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AWMGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected ac.soton.awm.parser.antlr.internal.InternalAWMParser createParser(XtextTokenStream stream) {
		return new ac.soton.awm.parser.antlr.internal.InternalAWMParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public AWMGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AWMGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
