/*
 * generated by Xtext
 */
package ac.soton.awm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

import ac.soton.awm.ui.syntaxcolor.AWMAntlrTokenToAttributeIdMapper;
import ac.soton.awm.ui.syntaxcolor.AWMLexicalHighlightingConfiguration;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AWMUiModule extends ac.soton.awm.ui.AbstractAWMUiModule {
	public AWMUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IHighlightingConfiguration> bindILexicalHighlightingConfiguration() {
		return AWMLexicalHighlightingConfiguration.class;
	}

	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return AWMAntlrTokenToAttributeIdMapper.class ;
	}
}
