/*
 * generated by Xtext
 */
package ac.soton.awm.validation

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class AWMValidator extends AbstractAWMValidator {

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

//	@Check
//	def checkInstructionRegister(Instruction instruction) {
//		if (instruction instanceof Load) {
//			val reg = (instruction as Load).register
//			if (reg == 'r1')
//				warning("Register should be unique between processes", instruction, AWMPackage.Literals.LOAD__REGISTER)
//		}
//	}
}
