/*
 * generated by Xtext
 */
package ac.soton.awm.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractAWMValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(ac.soton.awm.aWM.AWMPackage.eINSTANCE);
		return result;
	}
}
