/*
 * generated by Xtext
 */
package ac.soton.awm.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import ac.soton.awm.ui.internal.AWMActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AWMExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AWMActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AWMActivator.getInstance().getInjector(AWMActivator.AC_SOTON_AWM_AWM);
	}
	
}
